language: go

go:
  - 1.2

before_script:
  - psql -c 'create database appmon_test;' postgres

env:
  - PGDATABASE=appmon_test PGUSER=postgres

script:
  - go test -test.initschema -test.dropschema -test.v
